### ISSUE TITLE
Wildcard for email address

### ISSUE THREAD

**Issue by dmhumph** [daskeyboard/daskeyboard-applet--gmail#1]
Create a way to wildcard email address spaces rather than just using an individual email account.  

Example:

*domain.com

**Comment by corykim** [comment]
I'm pretty sure that already works. I tested it by typing in only "domain" (the domain of one of my email accounts) and it notified me when I sent an email from that domain. Under the covers, it uses the Google API to search emails. It should use the same matching logic that happens in gmail itself, if you use the `from:` search term.

**Comment by dmhumph** [comment]
Thank you for this information, and I confirmed that this works for "domain.com" without the "*" for a wildcard.  I think it might be helpful to put something in the documentation about this feature as well.
