### ISSUE TITLE
Unable to sign in with Google

### ISSUE THREAD

**Issue by dave10au** [daskeyboard/daskeyboard-applet--gmail#2]
When the applet v1.1.4 is installed and  gmail account details are entered the error appears stating
"Sign in with Google temporarily disabled for this app
This app has not yet been verified by Google in order to use Google Sign in."
From what I have read it seems like there is some limit of authentications against the app before you receive this message and are required to get the app verified by google.
There doesn't look to be a way to bypass this problem.

**Comment by fadedgiant** [comment]
I am experiencing this same error.
